export { default as useLoginSchema } from './loginSchema';
export { default as useSignupSchema } from './registrationSchema';
export { default as useForgotPasswordSchema } from './forgotPasswordSchema';
export { default as useUpdatePasswordSchema } from './updatePasswordSchema';
export { default as useEditProfileSchema } from './editProfileSchema';
export { default as useProfileSchema } from './profileSchema';
export { default as useMovieSchema } from './movieSchema';
export { default as useQuoteSchema } from './quoteSchema';
export { default as profileSchema } from './profileSchema';
